import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useEffect(() => {
    localStorage.removeItem('token')
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={[styles.main]}>
        <div className={styles.description}>
          <p>
            Matrix Lv 2 Test
          </p>
          <div>
            <a
              href="https://github.com/azwar"
              target="_blank"
              rel="noopener noreferrer"
            >
              By Azwar Akbar
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/images/logo-matrix.jpg"
            alt="Matrix Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <Link
            href="/login"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Let's start <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Sign in first to be able to use feature find item coordinate from matrix.
            </p>
          </Link>
        </div>
      </main>
    </>
  )
}
